HELP DESCRIBE STUDENT;
SELECT * FROM GRADE;
SELECT * FROM STUDENT;
SELECT * FROM FACULTY WHERE fid!=1010 AND fid!=1020;
SELECT * FROM FACULTY WHERE fid>=1050 OR fid<1020;
SELECT * FROM FACULTY WHERE fid<=1030 OR fid>1050;
SELECT * FROM ENROLLED;
QUIT;
